// src/service/ProductService.js

export const ProductService = {
  getProducts: async () => {
    // Example data, replace this with your actual data fetching logic
    return [
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Open",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "On Hold",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      {
        invoice: "12386",
        customer: "Charly dues",
        price: "$2652",
        from: "Russia",
        status: "Process",
      },
      
      
    ];
  },
};
